config/routes.rb
Foundation::Application.routes.draw do

  devise_for :staffs, :except => :create

  resources :staffs

  resources :finances

  resources :staffobjectjournals

  resources :posts

  resources :data_files do
    collection { post :upload }
  end

  resources :uploads

  resources :staff_task_journals

  resources :tasks

  resources :workobjects

  resources :map

  root to: "map#index"

end

app/models/staff.rb
class Staff < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :omniauthable and :registerable
  devise :database_authenticatable, :recoverable,
          :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :password, :password_confirmation, :remember_me,
                  :birthday, :fname, :lname, :mname, :passport, :position,
                  :skill, :login, :email, :phone1, :phone2, :admin
#  validates :birthday, presence: true
  validates :fname, presence: true
  validates :lname, presence: true
#  validates :mname, presence: true
#  validates :passport, presence: true
#  validates :position, presence: true
#  validates :skill, presence: true

  validates_presence_of :login
  validates_uniqueness_of :login, :email, :case_sensitive => false

  def fullname
     res=read_attribute(:lname)+" "+read_attribute(:fname)+" "+read_attribute(:mname)
     res+=", "+read_attribute(:position) unless read_attribute(:position).nil?
     res
  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found
  before_filter :authorize, :except => [:index, :show]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @staffs }
    end
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
    @staff = Staff.find(params[:id])
    @staff_tasks = StaffTaskJournal.where(staff_id: params[:id])
    @staff_objects = Staffobjectjournal.where(staff_id: params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @staff }
    end
  end

  # GET /staffs/new
  # GET /staffs/new.json
  def new
    @staff = Staff.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @staff }
    end
  end

  # GET /staffs/1/edit
  def edit
    @staff = Staff.find(params[:id])
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(params[:staff])

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render json: @staff, status: :created, location: @staff }
      else
        format.html { render action: "new" }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /staffs/1
  # PUT /staffs/1.json
  def update
    @staff = Staff.find(params[:id])
    respond_to do |format|
      if @staff.update_without_password(params[:staff])
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff = Staff.find(params[:id])
    @staff.destroy

    respond_to do |format|
      format.html { redirect_to staffs_url }
      format.json { head :no_content }
    end
  end

  private
    def record_not_found
#:birthday, :fname, :lname, :mname, :passport, :position, :skill, :login, :password, :email, :phone1, :phone2
      write_attribute(:fname," ")
      write_attribute(:mname," ")
      write_attribute(:lname," ")
      write_attribute(:login," ")
    end

end

app/views/staffs/_form.html.erb
<%= form_for(@staff) do |f| %>
  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% @staff.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="large-6 columns">

  <div class="field">
    <b>Фамилия:</b>
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <b>Имя:</b>
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <b>Отчество:</b>
    <%= f.text_field :mname %>
  </div>
  <div class="field">
    <b>Должность:</b>
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <b>Дата рождения:</b>
    <input type=date name="staff[birthday]" value=<%=@staff.birthday%> placeholder="large-2.columns">
  </div>
</div>
  <div class="large-6 columns">
  <div class="field">
    <b>Паспорт:</b>
    <%= f.text_field :passport %>
  </div>
  <div class="field">
    <b>Email:</b>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <b>Phone:</b>
    <%= f.text_field :phone1 %>
  </div>
  <div class="field">
    <b>Login:</b>
    <%= f.text_field :login%>
  </div>
    <div class="field">
      <b>Admin:</b>
      <%= f.check_box :admin%>
    </div>
  <div class="field">
    <b>Password:</b>
    <%= f.text_field :password %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/staffs/_tasks.html.erb
<h1>Список задач</h1>

<table>
  <tr>
    <th>Описание</th>
    <th>Начало</th>
    <th>Окончание</th>
    <th></th>
    <th></th>
  </tr>

<% @staff_tasks.each do |st_task| %>
  <tr>
    <td><%= link_to Task.find(st_task.task_id).fullname, st_task %></td>
    <td><%= st_task.sdate %></td>
    <td><%= st_task.edate %></td>
    <td><%= link_to 'Edit', edit_task_path(st_task) %></td>
    <td><%= link_to 'Destroy', st_task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Добавить задачу', new_staff_task_journal_path, staff_id: 1 %>

app/views/staffs/_workobject.html.erb
<h4>Список Объектов</h4>

<table>
  <tr>
    <th>Объект</th>
    <th>Начало</th>
    <th>Окончание</th>
    <th></th>
    <th></th>
  </tr>

<% @staff_objects.each do |st_wo| %>
  <tr>
    <td><%= link_to Workobject.find(st_wo.workobject_id).fulladdr, st_wo %></td>
    <td><%= st_wo.sdate %></td>
    <td><%= st_wo.edate %></td>
    <td><%= link_to 'Edit', edit_staffobjectjournal_path(st_wo) %></td>
    <td><%= link_to 'Destroy', st_wo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Добавить Объект', new_staffobjectjournal_path, staff_id: 1 %>

app/views/staffs/edit.html.erb
<h1>Редактирование данных сотрудника</h1>

<%= render 'form' %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

app/views/staffs/index.html.erb
<div class="row display">
 <div class="small-5 columns">
  <h4>Список сотрудников</h4>
 </div>
 <div class="small-2 small-offset-5 columns">
  <%= link_to 'Добавить сотрудника', new_staff_path, class: "button radius"  %>
 </div>
</div>

<% if flash[:error] %>
    <div id="error_explanation"><h2><%= flash[:error] %></h2></div>
<% end %>

<table>
  <tr>
    <th>ФИО</th>
    <th>Должность</th>
    <th>Дата рождения</th>
    <th></th>
  </tr>

<% @staffs.each do |staff| %>
  <tr>
    <td><%= link_to staff.lname+" "+staff.fname+" "+staff.mname, staff %></td>
    <td><%= staff.position %></td>
    <td><%= staff.birthday %></td>
    <td><%= link_to tag("img", { :src => "/images/button_edit.gif", :title =>'Edit', :alt=>'Edit',:border=>0,:size=>"17x17"}, false) , edit_staff_path(staff) %>
      <%= link_to tag("img", { :src => "/images/button_drop.gif", :title =>'Destroy', :alt=>'Destroy',:border=>0}, false), staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>

  </tr>
<% end %>
</table>

app/views/staffs/new.html.erb
<h1>New staff</h1>

<%= render 'form' %>

<%= link_to 'Back', staffs_path %>

app/views/staffs/show.html.erb
<div class="row display">
 <div class="small-6 columns">

<p id="notice"><%= notice %></p>

<p>
  <b>Фамилия:</b>
  <%= @staff.lname %>
</p>

<p>
  <b>Имя:</b>
  <%= @staff.fname %>
</p>

<p>
  <b>Отчество:</b>
  <%= @staff.mname %>
</p>

<p>
  <b>Должность:</b>
  <%= @staff.position %>
</p>

<p>
  <b>Дата рождения:</b>
  <%= @staff.birthday %>
</p>

<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>

</div>
 <div class="small-6 columns">
<%= render 'workobject' %>
</div>
</div>