config/routes.rb
Foundation::Application.routes.draw do

  devise_for :staffs, :except => :create

  resources :staffs

  resources :finances

  resources :staffobjectjournals

  resources :posts

  resources :data_files do
    collection { post :upload }
  end

  resources :uploads

  resources :staff_task_journals

  resources :tasks

  resources :workobjects

  resources :map

  root to: "map#index"

end

app/models/finance.rb
class Finance < ActiveRecord::Base
  attr_accessible :cost_type, :fin_item, :staff_id, :staff_item, :workobject_id, :summa, :d1, :d2, :remark, :invoice

  def self.search(search)
    if search
      where('wo_full LIKE ? OR staff_full LIKE ? OR cost_type LIKE ? OR fin_item LIKE ? OR staff_item like ? OR remark like ? OR invoice like ?', "%#{search}%","%#{search}%","%#{search}%","%#{search}%","%#{search}%","%#{search}%","%#{search}%")
    else
      scoped
    end
  end

end

app/controllers/finances_controller.rb
class FinancesController < ApplicationController
  # GET /finances
  # GET /finances.json
  include FinancesHelper
  def index
    @finances = Finance.joins("left join workobjects wo on wo.id=finances.workobject_id").joins("left join staffs ss1 on ss1.id=finances.staff_id").select("finances.id id,wo.name || ', '||wo.city||', '||wo.address wo_full,ss1.lname || ' ' || ss1.fname staff_full,finances.cost_type cost_type,finances.fin_item fin_item,finances.staff_item staff_item,finances.summa,finances.d1,finances.d2,finances.remark,finances.invoice").search(params[:search]).order(sort_column + " " + sort_direction)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @finances }
    end
  end

  # GET /finances/1
  # GET /finances/1.json
  def show
    @finance = Finance.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @finance }
    end
  end

  # GET /finances/new
  # GET /finances/new.json
  def new
    @finance = Finance.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @finance }
    end
  end

  # GET /finances/1/edit
  def edit
    @finance = Finance.find(params[:id])
  end

  # POST /finances
  # POST /finances.json
  def create
    @finance = Finance.new(params[:finance])

    respond_to do |format|
      if @finance.save
        format.html { redirect_to finances_url, notice: 'Finance was successfully created.' }
        format.json { render json: finances_url, status: :created, location: @finance }
      else
        format.html { render action: "new" }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /finances/1
  # PUT /finances/1.json
  def update
    @finance = Finance.find(params[:id])

    respond_to do |format|
      if @finance.update_attributes(params[:finance])
        format.html { redirect_to finances_url, notice: 'Finance was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /finances/1
  # DELETE /finances/1.json
  def destroy
    @finance = Finance.find(params[:id])
    @finance.destroy

    respond_to do |format|
      format.html { redirect_to finances_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/finances_helper.rb
# -*- encoding : utf-8 -*-
module FinancesHelper
 def sort_column
    ["wo_full","staff_full","cost_type","fin_item","staff_item","summa"].include?(params[:sort]) ? params[:sort] : "id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

  def sortable(column, title = nil,search)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction, :search => search}, {:class => css_class}
  end

  def cost_type_array
    %w[Финансы Кадры]
  end

  def fin_item_array
    ["Расчет субподряда","Командировочные","Транспортные расходы","Проживание","Оборудование","Аванс","Кредит","зп.выплата","Премия","Услуги","товары/материалы","Аванс подрядчику","аренда помещения/офиса","Разное","связь мобил","Коммунальные услуги"]
  end
end

app/views/finances/_form.html.erb
<%= form_for(@finance) do |f| %>
  <% if @finance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@finance.errors.count, "error") %> prohibited this finance from being saved:</h2>

      <ul>
      <% @finance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="large-6 columns">
    <b>Объект:</b><br>
    <%= f.select :workobject_id, Workobject.all.collect {|wo| [wo.name+", "+wo.city+", "+wo.address,wo.id] }, {include_blank: true} %>
  </div>
  </div>
<div class="row">
  <div class="large-6 columns">
    <b>Сотрудник:</b><br>
    <%= f.select :staff_id, Staff.all.collect {|st| [st.fullname ,st.id] }, {include_blank: true} %>
  </div>
</div>
  <div class="row">
<div class="large-6 columns">
    <b>Тип:</b><br>
    <%= f.select :cost_type, cost_type_array.collect {|ct| [ct,ct] } %>
  </div>
</div>
<div class="row">
<div class="large-6 columns">
    <b>Статья расходов:</b><br />
    <%= f.select :fin_item, fin_item_array.collect {|ct| [ct,ct] }, {include_blank: true} %>
  </div>
</div>
<div class="row">
  <div class="large-6 columns">
    <b>Сумма:</b><br />
    <%= f.text_field :summa %>
  </div>
</div>
<div class="row">
  <div class="large-6 columns">
    <div class="large-3 columns">
      <b>Дата1:</b>
      <input type=date name=finance[d1] value="<%=@finance.d1%>" size=10>
    </div>
    <div class="large-3 columns">
      <b>Дата2:</b>
      <input type=date name=finance[d2] value="<%=@finance.d2%>" size=10>
    </div>
  </div>
</div>
<div class="row">
  <div class="large-6 columns">
    <b>Примечание:</b><br />
    <%= f.text_area :remark, cols: 40 %>
  </div>
</div>
<div class="row">
  <div class="large-6 columns">
    <b>Счет/чек:</b><br />
    <%= f.text_field :invoice %>
  </div>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/finances/edit.html.erb
<h4>Редактирование финансовой записи</h4>

<%= render 'form' %>

<%= link_to 'Show', @finance %> |
<%= link_to 'Back', finances_path %>

app/views/finances/index.html.erb
<p id="notice"><%= notice %></p>
<%= form_tag finances_path, :method => 'get' do %>
<div class="row display">
 <div class="small-1 columns">
  <h4>Финансы</h4>
 </div>
    <div class="small-3 columns">
        <%= hidden_field_tag :direction, params[:direction] %>
        <%= hidden_field_tag :sort, params[:sort] %>
        <input name="search" size="20" type="text" value=<%=params[:search]%>>
    </div>
    <div class="small-1 columns">
          <%= submit_tag "Найти", :name => nil %>
    </div>
 <div class="small-7 columns">
  <%= link_to 'Добавить запись', new_finance_path, class: "button radius"  %>
 </div>
</div>
<% end %>
<table>
  <tr>
    <th><%= sortable "wo_full", "Объект", params[:search] %></th>
    <th><%= sortable "staff_full","Сотрудник", params[:search] %></th>
    <th><%= sortable "cost_type","Тип", params[:search] %></th>
    <th><%= sortable "fin_item","Статья расходов", params[:search] %></th>
    <th><%= sortable "staff_item","Тип выплат", params[:search] %></th>
    <th><%= sortable "summa","Сумма", params[:search] %></th>
    <th><%= sortable "d1","Дата1", params[:search] %></th>
    <th><%= sortable "d2","Дата2", params[:search] %></th>
    <th><%= sortable "remark","Примечение", params[:search] %></th>
    <th><%= sortable "invoice","Счет/чек", params[:search] %></th>
    <th></th>
  </tr>

<% @finances.each do |finance| %>
  <tr>
    <td><%= finance.wo_full.nil? ? "" : finance.wo_full[0..40]<<"..." %></td>
    <td><%= finance.staff_full %></td>
    <td><%= finance.cost_type %></td>
    <td><%= finance.fin_item %></td>
    <td><%= finance.staff_item %></td>
    <td><%= finance.summa %></td>
    <td><%= finance.d1 %></td>
    <td><%= finance.d2 %></td>
    <td><%= finance.remark %></td>
    <td><%= finance.invoice %></td>
    <td><%= link_to tag("img", { :src => "/images/button_edit.gif", :title =>'Edit', :alt=>'Edit',:border=>0,:size=>"17x17"}, false) ,  edit_finance_path(finance) %>
    <%= link_to tag("img", { :src => "/images/button_drop.gif", :title =>'Destroy', :alt=>'Destroy',:border=>0}, false), finance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/finances/new.html.erb
<h4>Добавление новой записи</h4>

<%= render 'form' %>

<%= link_to 'Back', finances_path %>

app/views/finances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Workobject:</b>
  <%= @finance.workobject_id %>
</p>

<p>
  <b>Staff:</b>
  <%= @finance.staff_id %>
</p>

<p>
  <b>Cost type:</b>
  <%= @finance.cost_type %>
</p>

<p>
  <b>Fin item:</b>
  <%= @finance.fin_item %>
</p>

<p>
  <b>Staff item:</b>
  <%= @finance.staff_item %>
</p>


<%= link_to 'Edit', edit_finance_path(@finance) %> |
<%= link_to 'Back', finances_path %>