config/routes.rb
Foundation::Application.routes.draw do

  devise_for :staffs, :except => :create

  resources :staffs

  resources :finances

  resources :staffobjectjournals

  resources :posts

  resources :data_files do
    collection { post :upload }
  end

  resources :uploads

  resources :staff_task_journals

  resources :tasks

  resources :workobjects

  resources :map

  root to: "map#index"

end

app/models/task.rb
class Task < ActiveRecord::Base
  after_initialize :default_values
  has_many :staff_task_journals, dependent: :destroy
  has_many :posts, dependent: :destroy
  belongs_to :staff

  attr_accessible :workobject_id, :description, :edate, :progress, :sdate, :state, :staff_id, :staff_from_id, :priority
  validates :description, presence: true
  validates :staff_id, presence: true
  validates :staff_from_id, presence: true

 
  def fullname
     wf = read_attribute(:workobject_id).nil? ? " " : Workobject.find(read_attribute(:workobject_id)).fulladdr
     read_attribute(:description)+", "+wf
  end

  def default_values
    self.state = "new" if self.state.nil? || self.state.empty?
  end

  def self.search(search)
    if search
     where('description LIKE ? OR sdate LIKE ? OR edate LIKE ? OR wo_fulladdr LIKE ? OR from_name LIKE ? OR to_name LIKE ?', "%#{search}%","%#{search}%","%#{search}%","%#{search}%","%#{search}%","%#{search}%")
      else
     scoped
    end
   end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found
  before_filter :authorize, :only => [:destroy]
  include WorkobjectsHelper
  include TasksHelper
  include Sms::SendSmsHelper
  helper_method :sort_column, :sort_direction



  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = if current_staff.admin?
     Task.joins("left join staffs ss1 on ss1.id=tasks.staff_id").joins("left join staffs ss2 on ss2.id=tasks.staff_from_id").joins("left join workobjects wo on wo.id=tasks.workobject_id").select("tasks.id id,tasks.description description,wo.id wo_id,wo.name || ', '||wo.city||', '||wo.address wo_fulladdr,ss2.lname || ' ' || ss2.fname from_name,ss1.lname || ' ' || ss1.fname to_name,tasks.sdate,tasks.edate,tasks.progress,tasks.state,tasks.priority").search(params[:search]).order(sort_column + " " + sort_direction)
        else
     Task.joins("left join staffs ss1 on ss1.id=tasks.staff_id").joins("left join staffs ss2 on ss2.id=tasks.staff_from_id").joins("left join workobjects wo on wo.id=tasks.workobject_id").select("tasks.id id,tasks.description,wo.id wo_id,wo.name || ', '||wo.city||', '||wo.address wo_fulladdr,ss2.lname || ' ' || ss2.fname from_name,ss1.lname || ' ' || ss1.fname to_name,tasks.sdate,tasks.edate,tasks.progress,tasks.state,tasks.priority").where(staff_id: current_staff.id).search(params[:search]).order(sort_column + " " + sort_direction + ",priority desc")
  end
      respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])
logger.debug "!!!!!!!!!!!!!!!!!!"+@task.inspect
    @task.update_attribute(:state, "2run") if @task.state=="3new" && current_staff.id==@task.staff_id
    task_deleg_f = TaskDelegate.where(task_id: @task.id).first
    @staff_from_fullname = Staff.exists?(@task.staff_from_id) ? Staff.find(@task.staff_from_id).fullname : ""
    @wo_fulladdr =  @task.workobject_id.nil? ?  "" : Workobject.find(@task.workobject_id).fulladdr
    @post = Post.new
    @upload = Upload.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])
    @task.staff_from_id = current_staff.id
    @task.state = "3new"

    respond_to do |format|
      if @task.save
        task_delegate = TaskDelegate.new
        task_delegate.staff_from = current_staff.id
        task_delegate.staff_to = params[:task]["staff_id"]
        task_delegate.task_id = @task.id
        task_delegate.when = Time.now
        if task_delegate.save
          Mailer.task_notification(Staff.find(params[:task]["staff_id"]),Staff.find(current_staff.id),@task).deliver
          sms_state = send_sms(Staff.find(task_delegate.staff_to),Staff.find(task_delegate.staff_from),@task.id) =~ /100/ ? "SMS send Ok" : "SMS not send"
          format.html { redirect_to @task, notice: 'Task was successfully created.<br>'+sms_state }
          format.json { render json: @task, status: :created, location: @task }
        else
          format.html { render action: "new" }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])
#    @task.staff_from_id = current_staff.id
    old_staff_id = @task.staff_id.nil? ? 0 : @task.staff_id
logger.debug "===== #{@task.staff_id.inspect} ====="
logger.debug "===== #{params[:task]["staff_id"].inspect} ====="
    respond_to do |format|
      if @task.update_attributes(params[:task])
        if !params[:task]["staff_id"].nil? && old_staff_id.to_i != params[:task]["staff_id"].to_i
          task_delegate = TaskDelegate.new
          task_delegate.staff_from = current_staff.id
          task_delegate.staff_to = params[:task]["staff_id"]
          task_delegate.task_id = @task.id
          task_delegate.when = Time.now
          Mailer.task_notification(Staff.find(task_delegate.staff_to),Staff.find(task_delegate.staff_from),@task)
          if task_delegate.save
            sms_state = send_sms(Staff.find(task_delegate.staff_to),Staff.find(task_delegate.staff_from),@task.id) =~ /100/ ? "SMS send Ok" : "SMS not send"
            format.html { redirect_to @task, notice: 'Task was successfully updated.<br>'+sms_state }
            format.json { head :no_content }
          else
            format.html { render action: "edit" }
            format.json { render json: @task.errors, status: :unprocessable_entity }
          end
        else
          format.html { redirect_to @task, notice: 'Task was successfully updated.' }
          format.json { head :no_content }
        end
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    if current_staff.admin?
      @task.destroy
      end
      respond_to do |format|
        format.html { redirect_to tasks_url }
        format.json { head :no_content }
      end
    end
  end

  private
    def record_not_found
     write_attribute(:description," ")
     write_attribute(:workobject_id,0)
    end
  def sort_column
    ["description","workobject_id","from_name","to_name","sdate","edate","progress","state","priority"].include?(params[:sort]) ? params[:sort] : "id"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

app/helpers/tasks_helper.rb
# -*- encoding : utf-8 -*-
require 'net/http'
require 'cgi'


module TasksHelper
  def sortable(column, title = nil,search)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction, :search => search}, {:class => css_class}
  end

  def reps_join_upload_hash(id)
    hh = Hash.new
    Post.connection.select_all("SELECT p.id,date(p.created_at) pd,p.text,p.staff_id FROM (SELECT date(created_at) dd FROM uploads WHERE task_id=#{id} UNION SELECT date(created_at) dd FROM posts WHERE task_id=#{id}) dd LEFT JOIN posts p ON dd.dd=pd WHERE p.task_id=#{id}").each do |row|
      hh[row["pd"]] = [[],[]] if hh[row["pd"]].nil?
      hh[row["pd"]][0].push([row["id"],row["text"],row["staff_id"]])
    end
    Post.connection.select_all("SELECT dd.dd,u.id,date(u.created_at) ud,u.filename,u.staff,u.size FROM (SELECT date(created_at) dd FROM uploads WHERE task_id=#{id} UNION SELECT date(created_at) dd FROM posts WHERE task_id=#{id}) dd LEFT JOIN uploads u ON dd.dd=ud WHERE u.task_id=#{id}").each do |row|
      hh[row["ud"]] = [[],[]] if hh[row["ud"]].nil?
      hh[row["ud"]][1].push([row["id"],row["filename"],row["staff"],row["size"]])
    end
    hh
  end
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <b>Описание:</b><br>
      <%= f.text_area :description, cols: 40 %>
    </div>
<script type="text/javascript">
$('task_description').keyup(function(){
        $(this).height(100);
        $(this).height(this.scrollHeight);
});
</script>
    <div class="field">
      <b>Сотрудник:</b><br>
      <%= f.select :staff_id, Staff.all.collect {|st| [st.fullname ,st.id] }, {include_blank: true} %>
    </div>
    <div class="field">
      <b>Объект:</b><br>
      <%= f.select :workobject_id, Workobject.all.collect {|wo| [wo.name+", "+wo.city+", "+wo.address,wo.id] }, {include_blank: true} %>
    </div>
    <div class="row">
      <div class="large-3 columns">
        <div class="field">
          <b>Начало:</b><br><input type=date name=task[sdate] value="<%=@task.sdate%>">
        </div>
      </div>
      <div class="large-3 columns">
        <div class="field">
          <b>Окончание:</b><br> <input type=date name=task[edate] value="<%=@task.edate%>">
        </div>
        <p>Date: <input type="text" class="datepicker"></p>
      </div>
    </div><br>
    <div class="field">
     <b>Выполнение:</b><br>
     <% 0.step(100,20) do |st| %>
       <%= f.radio_button :progress, st %><font style="background-color:<%=color_for_fontbg_hash[st]%>"><%=st%></font>
    <% end %>
    </div>
    <div class="field">
      <b>Статус:</b><br>
      <%= f.select :state, task_status_hash.each.collect {|key,value| [value,key]}%>
    </div>
    <div class="actions">
      <div class="field">
        <b>Приоритет:</b><br>
        <%= f.select :priority, task_priority_hash.each.collect {|key,value| [value,key]}%>
      </div>
      <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/tasks/_form_user.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row display">
 <div class="small-4 columns">
<fieldset>
    <legend><h4>Редактирование задачи</h4></legend>
<p>
  <b>Описание:</b>
  <%= @task.description %>
</p>
<% if ! @task.workobject_id.nil? %>
<p>
  <b>Объект:</b>
  <%= Workobject.find(@task.workobject_id).fulladdr%>
</p>
<% end %>
<p>
  <b>Начало:</b>
  <%= @task.sdate %>
</p>

<p>
  <b>Окончание:</b>
  <%= @task.edate %>
</p>

    <div class="field">
     <b>Выполение:</b><br>
     <% 0.step(100,20) do |st| %>
       <%= f.radio_button :progress, st %><font style="background-color:<%=color_for_fontbg_hash[st]%>"><%=st%></font>
    <% end %>
    </div>
    <div class="field">
      <b>Статус:</b><br>
      <%= f.select :state, task_status_hash.each.collect {|key,value| [value,key]}%>
    </div>
  <div class="field">
    <b>Приоритет:</b><br>
    <%= f.select :priority, task_priority_hash.each.collect {|key,value| [value,key]}%>
  </div>
    <div class="actions">
      <%= f.submit %>
    </div>
 </fieldset>
 </div>
</div>

<% end %>

app/views/tasks/_history.html.erb
<fieldset>
    <legend><h4>История</h4></legend>
<div class="row dot_line">
 <div class="small-4 columns"><b>Кто</b></div>
 <div class="small-4 columns"><b>Когда</b></div>
 <div class="small-4 columns"><b>Кому</b></div>
</div>

<% logger.debug "!!!" %>

<% TaskDelegate.where(task_id: params[:id]).each do |dlg| 
     color=cycle '#fff5ee', '#fff'
  %>
  <div class="row dot_line">
    <div class="small-4 columns" style="background-color:<%= color %>"><%= Staff.find(dlg.staff_from).fullname unless dlg.staff_from.nil? %></div>
    <div class="small-4 columns" style="background-color:<%= color %>"><%= dlg.created_at.strftime("%Y-%m-%d %H:%M") %></div>
    <div class="small-4 columns" style="background-color:<%= color %>"><%= Staff.find(dlg.staff_to).fullname unless dlg.staff_to.nil? %></div>
  </div>
<% end %>

  <div id=divdlg style="display:none">
    <%= form_for(@task) do |f| %>
      <div class="field">
        <b>Делегировать задачу сотруднику:</b><br>
        <%= f.select :staff_id, Staff.all.collect {|st| [st.fullname ,st.id] }, {include_blank: true} %>
        <div class="actions">
          <%= f.submit %>
        </div>
      </div>
    <% end %>
  </div>

<br>
<a href=# onclick="divdlg.style.display='';">Делегировать задачу</a>
</fieldset>

app/views/tasks/_index_admin.html.erb
<table>
  <tr>
    <th width=21%><%= sortable "description", "Описание", params[:search] %></th>
    <th width=21%><%= sortable "wo_fullname", "Объект", params[:search] %></th>
    <th width=15%><%= sortable "from_name", "Автор", params[:search] %></th>
    <th width=15%><%= sortable "to_name", "Исполнитель", params[:search] %></th>
    <th width=6%><%= sortable "sdate", "Начало", params[:search] %></th>
    <th width=6%><%= sortable "edate", "Окончание", params[:search] %></th>
    <th width=5%><%= sortable "progress", "% Выполнения", params[:search] %></th>
    <th width=6%><%= sortable "state", "Статус", params[:search] %></th>
    <th width=5%></th>
  </tr>

  <% @tasks.each do |task| %>
      <tr>
        <td width=21%><%= tag("img", { :src => "/images/warning.png", :title =>'Горящая', :alt=>'Горящая',:border=>0}, false) if task.priority=="burn" %>
          <%= link_to task.description[0..40]+"...", task,class: task.state[1..-1] %></td>
        <td width=21%><%= link_to @task_wo_fulladdr[0..40]+"...", workobject_path(@task_wo_id), class: task.state[1..-1] unless @task_wo_id.nil? %></td>
        <td width=15% class=<%=task.state[1..-1]%>><%= task.from_name %></td>
        <td width=15% class=<%=task.state[1..-1]%>><%= task.to_name %></td>
        <td width=6% class=<%=task.state[1..-1]%>><%= task.sdate %></td>
        <td width=6% class=<%=task.state[1..-1]%>><%= task.edate %></td>
        <td width=5% class=<%=task.state[1..-1]%>><%= task.progress %></td>
        <td width=6% class=<%=task.state[1..-1]%>><%= task_status_hash[task.state] %></td>
        <td width=5%><%= link_to tag("img", { :src => "/images/button_edit.gif", :title =>'Edit', :alt=>'Edit',:border=>0,:size=>"17x17"}, false) , edit_task_path(task) %>
          <%= link_to tag("img", { :src => "/images/button_drop.gif", :title =>'Destroy', :alt=>'Destroy',:border=>0}, false), task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

app/views/tasks/_index_user.erb
<table>
  <tr>
    <th width=30%><%= sortable "description", "Описание", params[:search] %></th>
    <th width=30%><%= sortable "wo_fullname", "Объект", params[:search] %></th>
    <th width=15%><%= sortable "from_name", "Автор", params[:search] %></th>
    <th width=7%><%= sortable "sdate", "Начало", params[:search] %></th>
    <th width=7%><%= sortable "edate", "Окончание", params[:search] %></th>
    <th width=6%><%= sortable "progress", "% Выполнения", params[:search] %></th>
    <th width=5%><%= sortable "state", "Статус", params[:search] %></th>
  </tr>

  <% @tasks.each do |task| %>
      <tr>
        <td width=28%><%= tag("img", { :src => "/images/warning.png", :title =>'Горящая', :alt=>'Горящая',:border=>0}, false) if task.priority=="burn" %>
          <%= link_to task.description[0..40]+"...", task,class: task.state[1..-1] %></td>
        <td width=28%><%= link_to task.wo_fulladdr[0..40]+"...", workobject_path(task.wo_id), class: task.state[1..-1] unless task.wo_id.nil? %></td>
        <td width=15% class=<%=task.state[1..-1]%>><%= task.from_name %></td>
        <td width=9% class=<%=task.state[1..-1]%>><%= task.sdate %></td>
        <td width=9% class=<%=task.state[1..-1]%>><%= task.edate %></td>
        <td width=6% class=<%=task.state[1..-1]%>><%= task.progress %></td>
        <td width=5% class=<%=task.state[1..-1]%>><%= task_status_hash[task.state] %></td>
      </tr>
  <% end %>
</table>

app/views/tasks/_index_user.html.erb
<table>
  <tr>
    <th width=30%><%= sortable "description", "Описание", params[:search] %></th>
    <th width=30%><%= sortable "wo_fullname", "Объект", params[:search] %></th>
    <th width=15%><%= sortable "from_name", "Автор", params[:search] %></th>
    <th width=7%><%= sortable "sdate", "Начало", params[:search] %></th>
    <th width=7%><%= sortable "edate", "Окончание", params[:search] %></th>
    <th width=6%><%= sortable "progress", "% Выполнения", params[:search] %></th>
    <th width=5%><%= sortable "state", "Статус", params[:search] %></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td width=28%><%= tag("img", { :src => "/images/warning.png", :title =>'Горящая', :alt=>'Горящая',:border=>0}, false) if task.priority=="burn" %>
   <%= link_to task.description[0..40]+"...", task,class: task.state[1..-1] %></td>
    <td width=28%><%= link_to task.wo_fulladdr[0..40]+"...", workobject_path(task.wo_id), class: task.state[1..-1] unless task.wo_id.nil? %></td>
    <td width=15% class=<%=task.state[1..-1]%>><%= task.from_name %></td>
    <td width=9%  class=<%=task.state[1..-1]%>><%= task.sdate %></td>
    <td width=9% class=<%=task.state[1..-1]%>><%= task.edate %></td>
    <td width=6% class=<%=task.state[1..-1]%>><%= task.progress %></td>
    <td width=5% class=<%=task.state[1..-1]%>><%= task_status_hash[task.state] %></td>
  </tr>
<% end %>
</table>

app/views/tasks/_posts.html.erb
<fieldset>
    <legend><h4>Комментарии</h4></legend>


<table width=100%>
  <tr><th width=10%>Дата</th><th width=60%>Текст</th><th width=30%>Файлы</th></tr>


<% reps_join_upload_hash(@task.id).each do |dd,row|
  %>
  <tr>
    <td width=10%><%= dd %></td>
    <td width=60%>
     <% row[0].each do |pp| %>
       <%=pp[1]%><br><b> =<%= Staff.find(pp[2]).lname if Staff.exists?(pp[2]) %></b><br>
     <% end %>
    </td>
    <td width=30%>
      <% row[1].each do |up| %>
        <img src=/paper-clip.png>
        <a href=/uploads/<%=up[0]%>><%= up[1]%></a> <%= (up[2].to_i/1024).to_i %>Kb</br>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

<br/>

<div id=addpost style="display:none">

<%= form_for(@post) do |f| %>
  <div class="field">
    <b>Текст</b>
    <%= f.text_area :text, cols: 40, rows: 20%>
  </div>
  <div class="actions">
    <%= f.submit "Добавить" %>
  </div> 
  <div>
   <a href=# onclick="addpost.style.display='none'" class=slist ><b>Отмена</b></a>
  </div>
  <%= hidden_field_tag :ref, "/tasks/#{params[:id]}" %>
  <%= f.hidden_field :task_id, :value=> params[:id]%>
 <% end %>
</div>

<div id=addfile  style="display:none">
<%= form_for(@upload) do |f| %>

  <div class="field">
    <b>Выберите файл</b><br />
    <%= f.file_field :filename %>
  </div>
  <div class="actions">
    <%= f.submit "Upload" %>
  </div>
  <div>
   <a href=# onclick="addfile.style.display='none'" class=slist ><b>Отмена</b></a>
  </div>
  <%= hidden_field_tag :ref, "/tasks/#{params[:id]}" %>
  <%= f.hidden_field :task_id, :value=>params[:id]%>
 <% end %>
</div>

<a href=# onclick="addpost.style.display='';addfile.style.display='none';"  class="button radius">Добавить комментарий</a>
<a href=# onclick="addfile.style.display='';addpost.style.display='none'"  class="button radius">Добавить файл</a>
</fieldset>

app/views/tasks/_staff.html.erb
<h4>Список сотрудников</h4>

<table>
  <tr>
    <th>ФИО </th>
    <th>Начало</th>
    <th>Окончание</th>
    <th></th>
    <th></th>
  </tr>

<% @staff_tasks.each do |st_task| %>
  <tr>
    <td><%= link_to Staff.find(st_task.staff_id).fullname, st_task %></td>
    <td><%= st_task.sdate %></td>
    <td><%= st_task.edate %></td>
    <td><%= link_to 'Edit', edit_task_path(st_task) %></td>
    <td><%= link_to 'Destroy', st_task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Добавить задачу', new_staff_task_journal_path, staff_id: 1 %>

app/views/tasks/edit.html.erb
<div class="row">
  <div class="large-6 columns">
   <fieldset>
    <legend><h4>Редактировать задачу</h4></legend>

<%= render 'form' %>

</fieldset>
  </div>
</div>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<% if flash[:error] %>
    <div id="error_explanation"><h2><%= flash[:error] %></h2></div>
<% end %>
<div class="row display">
  <div class="small-3 columns">
    <h4>Список задач</h4>
  </div>
  <div class="small-3 columns">
    <%= form_tag tasks_path, :method => 'get' do %>
        <%= hidden_field_tag :direction, params[:direction] %>
        <%= hidden_field_tag :sort, params[:sort] %>
        <input name="search" size="20" type="text" value=<%=params[:search]%>>
        </div>
        <div class="small-3 columns">
          <%= submit_tag "Найти", :name => nil %>
    <% end %>
    </div>
    <div class="small-3 columns">
      <%= link_to 'Добавить задачу', new_task_path, class: "button radius" %>
    </div>
    </div>
<% if current_staff.admin? %>
<%= render 'index_admin' %>
<% else %>
<%= render 'index_user' %>
<% end %>

app/views/tasks/new.html.erb
<div class="row">
  <div class="large-6 columns">
   <fieldset>
    <legend><h4>Добавить задачу</h4></legend>

<%= render 'form' %>

</fieldset>
  </div>
</div>
<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<div class="row display">
 <div class="small-4 columns">
<fieldset>
    <legend><h4>Задача</h4></legend>
<p>
  <b>Описание:</b>
  <%= @task.description %>
</p>
<p>
  <b>Автор:</b>
  <%= @staff_from_fullname %>
</p>
<% if ! @task.workobject_id.nil? %>
<p>
  <b>Объект:</b>
  <%= @wo_fulladdr%>
</p>
<% end %>
<p>
  <b>Начало:</b>
  <%= @task.sdate %>
</p>

<p>
  <b>Окончание:</b>
  <%= @task.edate %>
</p>

<p>
  <b>Выполения:</b>
  <font style="background-color:<%=color_for_fontbg_hash[@task.progress]%>"><%= @task.progress %>%</font>
</p>

<p>
  <b>Статус:</b>
  <%= task_status_hash[@task.state] %>
</p>

  <p>
    <b>Приоритет:</b>
    <%= task_priority_hash[@task.priority] %>
  </p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

</fieldset>
</div>

<div class="small-8 columns">
<%= render "history" %>
</div>
</div>
<div class="row display">
 <div class="small-12 columns">
   <%= render "posts" %>
 </div>
</div>