config/routes.rb
Foundation::Application.routes.draw do

  devise_for :staffs, :except => :create

  resources :staffs

  resources :finances

  resources :staffobjectjournals

  resources :posts

  resources :data_files do
    collection { post :upload }
  end

  resources :uploads

  resources :staff_task_journals

  resources :tasks

  resources :workobjects

  resources :map

  root to: "map#index"

end

app/models/upload.rb
class Upload < ActiveRecord::Base
  belongs_to :workobject
  belongs_to :staff
  attr_accessible :filename, :size, :workobject_id, :state, :staff, :task_id
#  has_attached_file :upload

  def save_upload(file,wo,staff_id)
    logger.debug "+++ #{file.inspect}\n"
    logger.debug "--- #{staff_id}\n"
    logger.debug "=== #{wo["task_id"].inspect}\n"
    name =  file.original_filename
    directory = "uploads/#{wo['workobject_id']}"
    directory = "uploads_task/#{wo['task_id']}" unless wo["task_id"].nil?
   # create the file path
    Dir.mkdir(directory) unless FileTest.directory?(directory)
    logger.debug "+++ #{name}\n"
    path = File.join(directory, name)
    # write the file
    File.open(path, "wb") { |f| f.write(file.read) }
    write_attribute(:filename, name)
    write_attribute(:workobject_id, wo["workobject_id"])
    write_attribute(:task_id, wo["task_id"])
    write_attribute(:size, File.size(path))
    write_attribute(:state, "new")
    write_attribute(:staff, @staff_id)
    save
  end

  def to_jq_upload
    {
      "name" => read_attribute(:filename),
      "size" => read_attribute(:size),
      "url" => upload.url(:original),
      "delete_url" => upload_path(self),
      "delete_type" => "DELETE" 
    }
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found
  before_filter :authorize, :except => [:index, :show, :new, :createa, :upload]

  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @uploads }
    end
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
    @upload = Upload.find(params[:id])
    directory = "uploads/#{@upload.workobject_id}"
    directory = "uploads_task/#{@upload.task_id}" unless @upload.task_id.nil?
    path = File.join(directory, @upload.filename)
    send_file path, :type => "Content-Type", :disposition => 'attachment; filename='+@upload.filename

#    respond_to do |format|
#      format.html # show.html.erb
#      format.json { render json: @upload }
#    end
  end

  # GET /uploads/new
  # GET /uploads/new.json
  def new
    @upload = Upload.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @upload }
    end
  end

  # GET /uploads/1/edit
  def edit
    @upload = Upload.find(params[:id])
  end

  def create
     #  @upload = Upload.new(params[upload])
     # POST /uploads
     # POST /uploads.json
    upld = Upload.new
    upld.save_upload(params[:upload][:filename],params[:upload],current_staff.id)
    respond_to do |format|
      format.html { redirect_to params[:ref], notice: 'Upload was successfully created.' }
#action: 'index', status: 303 
    end
  end

  # PUT /uploads/1
  # PUT /uploads/1.json
  def update
    @upload = Upload.find(params[:id])

    respond_to do |format|
      if @upload.update_attributes(params[:upload])
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload = Upload.find(params[:id])
    @upload.destroy
    respond_to do |format|
      format.html { redirect_to uploads_url }
      format.json { head :no_content }
    end
  end

  private
    def record_not_found
      write_attribute(:filename," ")
      write_attribute(:workobject_id,0)
    end

end

app/views/uploads/_form.html.erb
<%= form_for(@upload) do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% @upload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <b>Выберите файл</b><br />
    <%= f.file_field :filename %>
  </div>
  <div class="field">
    <% if ! params['workobject_id'].nil? %>
      <b>Объект</b><br />
      <%= f.select :workobject_id, Workobject.all.collect {|wo| [wo.fulladdr[0,60],wo.id] }, {include_blank: true,:selected=>params['workobject_id']} %>
      <%= hidden_field_tag :ref, "/workobjects/#{params[:id]}" %>
    <% end %>
    <% if ! params['task_id'].nil? %>
      <b>Задача</b><br />
      <%= f.select :task_id, Task.all.collect {|wo| [wo.description,wo.id] }, {include_blank: true,:selected=>params['task_id']} %>
      <%= hidden_field_tag :ref, "/tasks/#{params[:id]}" %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit "Upload" %>
  </div>
<% end %>

app/views/uploads/edit.html.erb
<h1>Editing upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<div class="row display">
 <div class="small-3 columns">
  <h4>Список документов</h4>
 </div>
 <div class="small-2 small-offset-7 columns">
  <%= link_to 'Новый файл', new_upload_path, class: "button radius"  %>
 </div>
</div>

<% if flash[:error] %>
    <div id="error_explanation"><h2><%= flash[:error] %></h2></div>
  <% end %>

<table>
  <tr>
    <th>Объект</th>
    <th>Имя файла</th>
    <th>Размер</th>
    <th>Дата</th>
    <th></th>
  </tr>
<% @uploads.each do |file| %>
  <tr>
    <% if file.workobject_id.nil? %>
       <td>%nbsp;</td>
    <% else %>
      <td><%= link_to Workobject.find(file.workobject_id).fulladdr, workobject_path(file.workobject_id)  %></td>
    <% end %>
    <td><%= link_to file.filename, upload_path(file) %></td>
    <td><%= file.size %></td>
    <td><%= file.created_at %></td>
    <td width=5%><%= link_to tag("img", { :src => "/images/button_edit.gif", :title =>'Edit', :alt=>'Edit',:border=>0,:size=>"17x17"}, false) , edit_upload_path(file) %>
      <%= link_to tag("img", { :src => "/images/button_drop.gif", :title =>'Destroy', :alt=>'Destroy',:border=>0}, false), file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/uploads/new.html.erb
<h1>Добавить файл</h1>

<%= render 'form' %>

<%= link_to 'Back', uploads_path %>

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @upload.filename %>
</p>

<p>
  <b>Size:</b>
  <%= @upload.size %>
</p>


<%= link_to 'Edit', edit_upload_path(@upload) %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/upload.html.erb
<h1>Список документов</h1>

<table>
  <tr>
    <th>Задача</th>
    <th>Имя файла</th>
    <th>Размер</th>
    <th>Дата</th>
    <th></th>
    <th></th>
  </tr>

<% @uploads.each do |file| %>
  <tr>
    <td><%= link_to Task.find(file.task_id).fullname, task_path(file.task_id)  %></td>
    <td><%= link_to file.filename, upload_path(file) %></td>
    <td><%= file.size %></td>
    <td><%= file.created_at %></td>
    <td><%= link_to 'Edit', edit_upload_path(file) %></td>
    <td><%= link_to 'Destroy', file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'Новый файл', new_upload_path %>